### ISSUE TITLE
duplicate comments in blog section

### ISSUE THREAD

**Issue by xbdirisxk** [Seb-GRAF/portfolio-v2#2]
Simple issue, I commented on one of your blogs and when I click post comment it didn't post directly then I click it again then refresh the page and two duplicate comments posted

**Comment by Seb-GRAF** [comment]
> Simple issue, I commented on one of your blogs and when I click post comment it didn't post directly then I click it again then refresh the page and two duplicate comments posted

Thanks you for your issue! I’ll try to replicate it and fix it. In the meantime I deleted the duplicate.
